### ISSUE TITLE
pycharm debug pycharm2.7 PyCharm debugger is stuck at "collecting data"

### ISSUE THREAD

**Issue by gnuhub** [gnuhub/sync-engine#17]
```
Connected to pydev debugger (build 181.5087.37)
('Connecting to ', '127.0.0.1', ':', '61452')
('Connected.',)
debugger: received >>501	1	0.1	UNIX
<<
Received command: CMD_VERSION 501	1	0.1	UNIX

sending cmd -->          CMD_VERSION 501	1	@@BUILD_NUMBER@@ 
debugger: received >>111	3	python-line	/Volumes/data/macbookair_data_180511/git/sync-engine/bin/inbox-auth	35	main	THREAD	None	None
<<
Received command: CMD_SET_BREAK 111	3	python-line	/Volumes/data/macbookair_data_180511/git/sync-engine/bin/inbox-auth	35	main	THREAD	None	None

Added breakpoint:/Volumes/data/macbookair_data_180511/git/sync-engine/bin/inbox-auth - line:35 - func_name:main

debugger: received >>122	5	django-VariableDoesNotExist
101	7	
146	9	SHOW_RETURN_VALUES	0
122	11	jinja2-TemplateError
<<
Received command: CMD_ADD_EXCEPTION_BREAK 122	5	django-VariableDoesNotExist

Received command: CMD_RUN 101	7	

Received command: CMD_SHOW_RETURN_VALUES 146	9	SHOW_RETURN_VALUES	0

Show return values: False

Received command: CMD_ADD_EXCEPTION_BREAK 122	11	jinja2-TemplateError

IDE_PROJECT_ROOTS ['/Volumes/data/macbookair_data_180511/git/sync-engine']

sending cmd -->    CMD_THREAD_CREATE 103	2	<xml><thread name="MainThread" id="pid_33743_id_4321645904" /></xml> 
sending cmd -->    CMD_THREAD_CREATE 103	4	<xml><thread name="DummyThread-6" id="pid_33743_id_4362386512" /></xml> 
sending cmd -->    CMD_THREAD_CREATE 103	6	<xml><thread name="DummyThread-7" id="pid_33743_id_4391629008" /></xml> 
sending cmd -->    CMD_THREAD_CREATE 103	8	<xml><thread name="DummyThread-8" id="pid_33743_id_4409949136" /></xml> 
```

**Comment by gnuhub** [comment]
```
WARN - ains.python.pydev.PyStackFrame - No connection (command:  114 ) 
com.jetbrains.python.debugger.PyDebuggerException: No connection (command:  114 )
	at com.jetbrains.python.debugger.pydev.AbstractCommand.execute(AbstractCommand.java:138)
	at com.jetbrains.python.debugger.pydev.RemoteDebugger.loadFrame(RemoteDebugger.java:142)
	at com.jetbrains.python.debugger.PyDebugProcess.loadFrame(PyDebugProcess.java:721)
	at com.jetbrains.python.debugger.PyStackFrame.a(PyStackFrame.java:135)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gnuhub** [comment]
![image](https://user-images.githubusercontent.com/1329093/41444421-81761386-7032-11e8-9b9b-8fe1c32af787.png)

**Comment by gnuhub** [comment]
## why?

**Comment by gnuhub** [comment]
## solution?

**Comment by gnuhub** [comment]
![image](https://user-images.githubusercontent.com/1329093/41444482-d805c0c0-7032-11e8-9d52-e3a4c12a981e.png)

**Comment by gnuhub** [comment]
Gevent compatible | If this checkbox is selected, the debugger will be compatible with the Gevent-monkeypatched code.
-- | --

**Comment by gnuhub** [comment]
https://www.jetbrains.com/help/pycharm/debugger-python.html

**Comment by gnuhub** [comment]
http://www.gevent.org/api/gevent.monkey.html

**Comment by gnuhub** [comment]
![image](https://user-images.githubusercontent.com/1329093/41444560-594df738-7033-11e8-9dba-3acdf3fbae66.png)
