### ISSUE TITLE
Missing config value for DB_POOL_SIZE. Run `sudo cp etc/config-dev.json /etc/inboxapp/config.json` and retry

### ISSUE THREAD

**Issue by gnuhub** [gnuhub/sync-engine#6]
```
/Volumes/data/anaconda/envs/py27/bin/python /Volumes/data/macbookair_data_180511/git/sync-engine/bin/inbox-start
No handlers could be found for logger "flanker.addresslib._parser.parser"
Traceback (most recent call last):
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/bin/inbox-start", line 28, in <module>
    from inbox.mailsync.service import SyncService
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/mailsync/service.py", line 11, in <module>
    from inbox.contacts.remote_sync import ContactSync
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/contacts/remote_sync.py", line 8, in <module>
    from inbox.models import Contact, Account
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/models/__init__.py", line 31, in <module>
    from inbox.models.backends import module_registry as backend_module_registry  # noqa
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/models/backends/__init__.py", line 8, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/util/misc.py", line 158, in register_backends
    modules = load_modules(base_name, base_path)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/util/misc.py", line 144, in load_modules
    full_module_name)
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/models/backends/gmail.py", line 12, in <module>
    from inbox.models.session import session_scope
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/models/session.py", line 11, in <module>
    from inbox.ignition import engine_manager
  File "/Volumes/data/anaconda/envs/py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/ignition.py", line 18, in <module>
    DB_POOL_SIZE = config.get_required('DB_POOL_SIZE')
  File "/Volumes/data/macbookair_data_180511/git/sync-engine/inbox/config.py", line 54, in get_required
    raise ConfigError('Missing config value for {0}.'.format(key))
inbox.config.ConfigError: Missing config value for DB_POOL_SIZE. Run `sudo cp etc/config-dev.json /etc/inboxapp/config.json` and retry.

Process finished with exit code 1
```

**Comment by gnuhub** [comment]
@click.option('-c', '--config', default=None,
              help='Path to JSON configuration file.')

**Comment by gnuhub** [comment]
if env in ['prod', 'staging']:
        base_cfg_path = [
            '/etc/inboxapp/secrets.yml',
            '/etc/inboxapp/config.json',
        ]
    else:
        v = {'env': env, 'srcdir': srcdir}
        base_cfg_path = [
            '{srcdir}/etc/secrets-{env}.yml'.format(**v),
            '{srcdir}/etc/config-{env}.json'.format(**v),
        ]

**Comment by gnuhub** [comment]
NYLAS_ENV=dev

**Comment by gnuhub** [comment]
![image](https://user-images.githubusercontent.com/1329093/41400028-87705ee8-6fee-11e8-872e-d92862f5c8e6.png)
